-- =============================================================================
-- Multi-gimnasio | Paso 1: DDL - Tabla GymUsers
-- PostgreSQL | Ejecutar en ventana de mantenimiento
-- =============================================================================
BEGIN;

DO $$
BEGIN
    IF EXISTS (
        SELECT 1
        FROM information_schema.tables
        WHERE table_schema = 'public'
          AND table_name = 'GymUsers'
    ) THEN
        RAISE NOTICE 'La tabla GymUsers ya existe. Paso 1 omitido.';
    ELSE
        RAISE NOTICE 'Creando tabla GymUsers...';
    END IF;
END $$;

CREATE TABLE IF NOT EXISTS "GymUsers" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "GymId" integer NOT NULL,
    "UserId" integer NOT NULL,
    "Rol" character varying(20) NOT NULL,
    "Activo" boolean NOT NULL DEFAULT TRUE,
    "FechaAsociacion" timestamp with time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT "PK_GymUsers" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_GymUsers_Gyms_GymId"
        FOREIGN KEY ("GymId") REFERENCES "Gyms" ("Id") ON DELETE CASCADE,
    CONSTRAINT "FK_GymUsers_Users_UserId"
        FOREIGN KEY ("UserId") REFERENCES "Users" ("Id") ON DELETE CASCADE
);

CREATE UNIQUE INDEX IF NOT EXISTS "IX_GymUsers_GymId_UserId"
    ON "GymUsers" ("GymId", "UserId");

CREATE INDEX IF NOT EXISTS "IX_GymUsers_UserId"
    ON "GymUsers" ("UserId");

COMMIT;

-- Rollback manual (solo si no se ejecutó el paso 2):
-- BEGIN;
-- DROP TABLE IF EXISTS "GymUsers";
-- COMMIT;
