// <auto-generated />
using System;
using GymAdmin.Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace GymAdmin.Infrastructure.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260515165945_EnableCascadeDeleteRoutines")]
    partial class EnableCascadeDeleteRoutines
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.11");

            modelBuilder.Entity("GymAdmin.Domain.Entities.Exercise", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        ;

                    b.Property<string>("Descripcion")
                        .HasMaxLength(1000)
                        ;

                    b.Property<string>("GrupoMuscular")
                        .IsRequired()
                        .HasMaxLength(100)
                        ;

                    b.Property<int>("GymId")
                        ;

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(150)
                        ;

                    b.Property<string>("VideoUrl")
                        .HasMaxLength(500)
                        ;

                    b.HasKey("Id");

                    b.HasIndex("GymId");

                    b.ToTable("Exercises", (string)null);
                });

            modelBuilder.Entity("GymAdmin.Domain.Entities.Gym", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        ;

                    b.Property<bool>("Activo")
                        .ValueGeneratedOnAdd()
                        
                        .HasDefaultValue(true);

                    b.Property<string>("ColorPrincipalHex")
                        .IsRequired()
                        .HasMaxLength(7)
                        ;

                    b.Property<string>("DuenoNombreApellido")
                        .IsRequired()
                        .HasMaxLength(200)
                        ;

                    b.Property<DateTime>("FechaCreacion")
                        .ValueGeneratedOnAdd()
                        
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<string>("LogoUrl")
                        .HasMaxLength(500)
                        ;

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(150)
                        ;

                    b.HasKey("Id");

                    b.ToTable("Gyms", (string)null);
                });

            modelBuilder.Entity("GymAdmin.Domain.Entities.Membership", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        ;

                    b.Property<int>("AlumnoId")
                        ;

                    b.Property<string>("Estado")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        
                        .HasDefaultValue("Activa");

                    b.Property<DateTime>("FechaCreacion")
                        .ValueGeneratedOnAdd()
                        
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<DateTime>("FechaInicio")
                        ;

                    b.Property<DateTime>("FechaVencimiento")
                        ;

                    b.Property<int>("GymId")
                        ;

                    b.Property<string>("Notas")
                        .HasMaxLength(1000)
                        ;

                    b.Property<int>("PlanId")
                        ;

                    b.HasKey("Id");

                    b.HasIndex("AlumnoId")
                        .IsUnique()
                        .HasFilter("\"Estado\" = 'Activa'");

                    b.HasIndex("Estado");

                    b.HasIndex("FechaVencimiento");

                    b.HasIndex("PlanId");

                    b.HasIndex("GymId", "AlumnoId");

                    b.ToTable("Memberships", (string)null);
                });

            modelBuilder.Entity("GymAdmin.Domain.Entities.MembershipPayment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        ;

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasMaxLength(20)
                        ;

                    b.Property<DateTime>("FechaCreacion")
                        .ValueGeneratedOnAdd()
                        
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<DateTime>("FechaPago")
                        ;

                    b.Property<int>("GymId")
                        ;

                    b.Property<int>("MembresiaId")
                        ;

                    b.Property<string>("MetodoPago")
                        .HasMaxLength(50)
                        ;

                    b.Property<decimal>("Monto")
                        .HasPrecision(10, 2)
                        ;

                    b.Property<string>("Notas")
                        .HasMaxLength(1000)
                        ;

                    b.Property<string>("Referencia")
                        .HasMaxLength(200)
                        ;

                    b.HasKey("Id");

                    b.HasIndex("FechaPago");

                    b.HasIndex("MembresiaId");

                    b.HasIndex("GymId", "MembresiaId");

                    b.ToTable("MembershipPayments", (string)null);
                });

            modelBuilder.Entity("GymAdmin.Domain.Entities.MembershipPlan", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        ;

                    b.Property<bool>("Activo")
                        .ValueGeneratedOnAdd()
                        
                        .HasDefaultValue(true);

                    b.Property<string>("Descripcion")
                        .HasMaxLength(1000)
                        ;

                    b.Property<int>("DuracionDias")
                        ;

                    b.Property<DateTime>("FechaCreacion")
                        .ValueGeneratedOnAdd()
                        
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<int>("GymId")
                        ;

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(150)
                        ;

                    b.Property<decimal>("Precio")
                        .HasPrecision(10, 2)
                        ;

                    b.HasKey("Id");

                    b.HasIndex("GymId", "Nombre");

                    b.ToTable("MembershipPlans", (string)null);
                });

            modelBuilder.Entity("GymAdmin.Domain.Entities.Routine", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        ;

                    b.Property<bool>("Activa")
                        .ValueGeneratedOnAdd()
                        
                        .HasDefaultValue(true);

                    b.Property<int>("DaysCount")
                        ;

                    b.Property<string>("Descripcion")
                        .HasMaxLength(1000)
                        ;

                    b.Property<DateTime>("FechaCreacion")
                        .ValueGeneratedOnAdd()
                        
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<int>("GymId")
                        ;

                    b.Property<bool>("IsByDays")
                        ;

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(200)
                        ;

                    b.Property<int>("ProfesorId")
                        ;

                    b.HasKey("Id");

                    b.HasIndex("GymId");

                    b.HasIndex("ProfesorId");

                    b.ToTable("Routines", (string)null);
                });

            modelBuilder.Entity("GymAdmin.Domain.Entities.RoutineExercise", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        ;

                    b.Property<string>("Bloque")
                        .IsRequired()
                        .HasMaxLength(50)
                        ;

                    b.Property<int>("DayNumber")
                        ;

                    b.Property<int?>("DescansoSegundos")
                        ;

                    b.Property<int>("EjercicioId")
                        ;

                    b.Property<string>("Observaciones")
                        .HasMaxLength(500)
                        ;

                    b.Property<int>("Orden")
                        ;

                    b.Property<decimal?>("Peso")
                        .HasPrecision(8, 2)
                        ;

                    b.Property<int>("Repeticiones")
                        ;

                    b.Property<int>("RutinaId")
                        ;

                    b.Property<int>("Series")
                        ;

                    b.HasKey("Id");

                    b.HasIndex("EjercicioId");

                    b.HasIndex("RutinaId", "Orden")
                        .IsUnique();

                    b.ToTable("RoutineExercises", (string)null);
                });

            modelBuilder.Entity("GymAdmin.Domain.Entities.StudentRoutine", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        ;

                    b.Property<bool>("Activa")
                        .ValueGeneratedOnAdd()
                        
                        .HasDefaultValue(true);

                    b.Property<int>("AlumnoId")
                        ;

                    b.Property<DateTime>("FechaAsignacion")
                        .ValueGeneratedOnAdd()
                        
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<int>("GymId")
                        ;

                    b.Property<int>("RutinaId")
                        ;

                    b.HasKey("Id");

                    b.HasIndex("GymId");

                    b.HasIndex("RutinaId");

                    b.HasIndex("AlumnoId", "RutinaId")
                        .IsUnique();

                    b.ToTable("StudentRoutines", (string)null);
                });

            modelBuilder.Entity("GymAdmin.Domain.Entities.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        ;

                    b.Property<bool>("Activo")
                        ;

                    b.Property<string>("Apellido")
                        .IsRequired()
                        .HasMaxLength(100)
                        ;

                    b.Property<bool>("DebeCambiarPassword")
                        ;

                    b.Property<string>("Dni")
                        .IsRequired()
                        .HasMaxLength(20)
                        ;

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(200)
                        ;

                    b.Property<DateTime>("FechaCreacion")
                        .ValueGeneratedOnAdd()
                        
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<string>("GoogleId")
                        .HasMaxLength(200)
                        ;

                    b.Property<int>("GymId")
                        ;

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        ;

                    b.Property<string>("PasswordHash")
                        ;

                    b.Property<string>("RefreshToken")
                        .HasMaxLength(500)
                        ;

                    b.Property<DateTime?>("RefreshTokenExpiracion")
                        ;

                    b.Property<string>("Rol")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        
                        .HasDefaultValue("Alumno");

                    b.HasKey("Id");

                    b.HasIndex("Dni")
                        .IsUnique();

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("GymId");

                    b.ToTable("Users", (string)null);
                });

            modelBuilder.Entity("GymAdmin.Domain.Entities.Exercise", b =>
                {
                    b.HasOne("GymAdmin.Domain.Entities.Gym", "Gym")
                        .WithMany("Exercises")
                        .HasForeignKey("GymId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Gym");
                });

            modelBuilder.Entity("GymAdmin.Domain.Entities.Membership", b =>
                {
                    b.HasOne("GymAdmin.Domain.Entities.User", "Alumno")
                        .WithMany("Membresias")
                        .HasForeignKey("AlumnoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("GymAdmin.Domain.Entities.Gym", "Gym")
                        .WithMany("Memberships")
                        .HasForeignKey("GymId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("GymAdmin.Domain.Entities.MembershipPlan", "Plan")
                        .WithMany("Membresias")
                        .HasForeignKey("PlanId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Alumno");

                    b.Navigation("Gym");

                    b.Navigation("Plan");
                });

            modelBuilder.Entity("GymAdmin.Domain.Entities.MembershipPayment", b =>
                {
                    b.HasOne("GymAdmin.Domain.Entities.Gym", "Gym")
                        .WithMany("MembershipPayments")
                        .HasForeignKey("GymId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("GymAdmin.Domain.Entities.Membership", "Membresia")
                        .WithMany("Pagos")
                        .HasForeignKey("MembresiaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Gym");

                    b.Navigation("Membresia");
                });

            modelBuilder.Entity("GymAdmin.Domain.Entities.MembershipPlan", b =>
                {
                    b.HasOne("GymAdmin.Domain.Entities.Gym", "Gym")
                        .WithMany("MembershipPlans")
                        .HasForeignKey("GymId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Gym");
                });

            modelBuilder.Entity("GymAdmin.Domain.Entities.Routine", b =>
                {
                    b.HasOne("GymAdmin.Domain.Entities.Gym", "Gym")
                        .WithMany("Routines")
                        .HasForeignKey("GymId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("GymAdmin.Domain.Entities.User", "Profesor")
                        .WithMany("RutinasCreadas")
                        .HasForeignKey("ProfesorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Gym");

                    b.Navigation("Profesor");
                });

            modelBuilder.Entity("GymAdmin.Domain.Entities.RoutineExercise", b =>
                {
                    b.HasOne("GymAdmin.Domain.Entities.Exercise", "Ejercicio")
                        .WithMany("RutinaEjercicios")
                        .HasForeignKey("EjercicioId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("GymAdmin.Domain.Entities.Routine", "Rutina")
                        .WithMany("Ejercicios")
                        .HasForeignKey("RutinaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Ejercicio");

                    b.Navigation("Rutina");
                });

            modelBuilder.Entity("GymAdmin.Domain.Entities.StudentRoutine", b =>
                {
                    b.HasOne("GymAdmin.Domain.Entities.User", "Alumno")
                        .WithMany("RutinasAsignadas")
                        .HasForeignKey("AlumnoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("GymAdmin.Domain.Entities.Gym", "Gym")
                        .WithMany("StudentRoutines")
                        .HasForeignKey("GymId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("GymAdmin.Domain.Entities.Routine", "Rutina")
                        .WithMany("AlumnosAsignados")
                        .HasForeignKey("RutinaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Alumno");

                    b.Navigation("Gym");

                    b.Navigation("Rutina");
                });

            modelBuilder.Entity("GymAdmin.Domain.Entities.User", b =>
                {
                    b.HasOne("GymAdmin.Domain.Entities.Gym", "Gym")
                        .WithMany("Users")
                        .HasForeignKey("GymId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Gym");
                });

            modelBuilder.Entity("GymAdmin.Domain.Entities.Exercise", b =>
                {
                    b.Navigation("RutinaEjercicios");
                });

            modelBuilder.Entity("GymAdmin.Domain.Entities.Gym", b =>
                {
                    b.Navigation("Exercises");

                    b.Navigation("MembershipPayments");

                    b.Navigation("MembershipPlans");

                    b.Navigation("Memberships");

                    b.Navigation("Routines");

                    b.Navigation("StudentRoutines");

                    b.Navigation("Users");
                });

            modelBuilder.Entity("GymAdmin.Domain.Entities.Membership", b =>
                {
                    b.Navigation("Pagos");
                });

            modelBuilder.Entity("GymAdmin.Domain.Entities.MembershipPlan", b =>
                {
                    b.Navigation("Membresias");
                });

            modelBuilder.Entity("GymAdmin.Domain.Entities.Routine", b =>
                {
                    b.Navigation("AlumnosAsignados");

                    b.Navigation("Ejercicios");
                });

            modelBuilder.Entity("GymAdmin.Domain.Entities.User", b =>
                {
                    b.Navigation("Membresias");

                    b.Navigation("RutinasAsignadas");

                    b.Navigation("RutinasCreadas");
                });
#pragma warning restore 612, 618
        }
    }
}
